const User = require('../models/userModel');
const UserDetails = require('../models/userDetailsModel');

class AnniversaryAnnouncementService {
  /**
   * Generate automatic anniversary announcements for today
   * @param {string} userTeam - Team of the requesting user (SD or KAP)
   * @returns {Array} Array of anniversary announcements
   */
  async getTodayAnniversaryAnnouncements(userTeam = null) {
    try {
      const today = new Date();
      const todayMonth = today.getMonth() + 1; // 1-12
      const todayDay = today.getDate();
      
      (`Checking anniversaries for today: ${todayDay}/${todayMonth}/${today.getFullYear()}`);
      
      const announcements = [];
      
      // Also check yesterday for debugging (Sept 15 vs Sept 16 issue)
      const yesterday = new Date(today);
      yesterday.setDate(yesterday.getDate() - 1);
      const yesterdayMonth = yesterday.getMonth() + 1;
      const yesterdayDay = yesterday.getDate();
      (`Also checking yesterday: ${yesterdayDay}/${yesterdayMonth}/${yesterday.getFullYear()}`);
      
      // Check both today and yesterday for work anniversaries
      const todayWorkAnniv = await this.getWorkAnniversaryAnnouncements(todayMonth, todayDay, userTeam);
      const yesterdayWorkAnniv = await this.getWorkAnniversaryAnnouncements(yesterdayMonth, yesterdayDay, userTeam);
      (`Today work anniversaries: ${todayWorkAnniv.length}`);
      (`Yesterday work anniversaries: ${yesterdayWorkAnniv.length}`);
      
      // 1. Get Birthday Announcements
      const birthdayAnnouncements = await this.getBirthdayAnnouncements(todayMonth, todayDay, userTeam);
      announcements.push(...birthdayAnnouncements);
      
      // 2. Get Work Anniversary Announcements
      const workAnniversaryAnnouncements = await this.getWorkAnniversaryAnnouncements(todayMonth, todayDay, userTeam);
      announcements.push(...workAnniversaryAnnouncements);
      
      // 3. Get Marriage Anniversary Announcements
      const marriageAnniversaryAnnouncements = await this.getMarriageAnniversaryAnnouncements(todayMonth, todayDay, userTeam);
      announcements.push(...marriageAnniversaryAnnouncements);
      
      return announcements;
    } catch (error) {
      console.error('Error generating anniversary announcements:', error);
      return [];
    }
  }

  /**
   * Get birthday announcements for today
   * @param {number} month - Month to check
   * @param {number} day - Day to check  
   * @param {string} userTeam - Team filter (SD or KAP)
   */
  async getBirthdayAnnouncements(month, day, userTeam = null) {
    try {
      const query = {
        $expr: {
          $and: [
            { $eq: [{ $month: "$dateOfBirth" }, month] },
            { $eq: [{ $dayOfMonth: "$dateOfBirth" }, day] }
          ]
        },
        isDeleted: false,
        dateOfBirth: { $exists: true, $ne: null },
        status: { $in: ["probation", "onroll"] }
      };

      // Add team filter if specified
      if (userTeam) {
        query.team = userTeam;
      }

      const birthdayUsers = await User.find(query)
        .select('firstName lastName employeeId dateOfBirth department team')
        .populate('department', 'name');
      
      return birthdayUsers.map(user => {
        const age = new Date().getFullYear() - new Date(user.dateOfBirth).getFullYear();
        return {
          _id: `birthday-${user._id}`,
          title: `🎂 Happy Birthday ${user.firstName} ${user.lastName}!`,
          content: `Join us in celebrating ${user.firstName} ${user.lastName}'s birthday today! Let's make this special day memorable for our amazing team member. 🎉`,
          date: new Date(),
          time: "09:00", // 24-hour format for proper sorting
          category: "general",
          departmentId: null,
          createdBy: {
            firstName: "System",
            lastName: "Auto",
            employeeId: "AUTO-BIRTHDAY",
            id: "system-birthday"
          },
          expireInHours: 24,
          isActive: true,
          isDeleted: false,
          isAutoGenerated: true,
          announcementType: "birthday",
          celebrantId: user._id,
          celebrantInfo: {
            name: `${user.firstName} ${user.lastName}`,
            employeeId: user.employeeId,
            department: user.department?.name
          }
        };
      });
    } catch (error) {
      console.error('Error fetching birthday announcements:', error);
      return [];
    }
  }

  /**
   * Get work anniversary announcements for today
   * @param {number} month - Month to check
   * @param {number} day - Day to check
   * @param {string} userTeam - Team filter (SD or KAP)
   */
  async getWorkAnniversaryAnnouncements(month, day, userTeam = null) {
    try {
      (`Looking for work anniversaries on ${day}/${month}`);
      
      // Get all users with hire dates for debugging
      const query = {
        isDeleted: false,
        hireDate: { $exists: true, $ne: null },
        status: { $in: ["probation", "onroll"] }
      };

      // Add team filter if specified
      if (userTeam) {
        query.team = userTeam;
      }

      const allUsersWithHireDate = await User.find(query)
        .select('firstName lastName employeeId hireDate department team')
        .populate('department', 'name');
      
      (`Found ${allUsersWithHireDate.length} users with hire dates`);
      
      // Filter users with work anniversaries today (handle timezone issues)
      const workAnniversaryUsers = allUsersWithHireDate.filter(user => {
        // Convert UTC date to local date for proper comparison
        const hireDate = new Date(user.hireDate);
        
        // Get local date components (this handles timezone conversion)
        const hireDateMonth = hireDate.getMonth() + 1; // 1-12
        const hireDateDay = hireDate.getDate();
        const hireYear = hireDate.getFullYear();
        const currentYear = new Date().getFullYear();
        
        (`User ${user.firstName} ${user.lastName}:`);
        (`  Original hire date: ${user.hireDate}`);
        (`  Parsed as local: ${hireDate}`);
        (`  Local date components: ${hireDateDay}/${hireDateMonth}/${hireYear}`);
        (`  Looking for: ${day}/${month}`);
        
        // Check if hire date month/day matches today and they've been here at least 1 year
        const isAnniversary = hireDateMonth === month && 
                             hireDateDay === day && 
                             hireYear < currentYear;
        
        (`  Is anniversary? ${isAnniversary}`);
        
        if (isAnniversary) {
          (`✅ Work anniversary found for ${user.firstName} ${user.lastName}!`);
        }
        
        return isAnniversary;
      });
      
      return workAnniversaryUsers.map(user => {
        const yearsOfService = new Date().getFullYear() - new Date(user.hireDate).getFullYear();
        const yearText = yearsOfService === 1 ? 'year' : 'years';
        
        return {
          _id: `work-anniversary-${user._id}`,
          title: `🏆 Work Anniversary - ${user.firstName} ${user.lastName}`,
          content: `Congratulations to ${user.firstName} ${user.lastName} on completing ${yearsOfService} ${yearText} with our organization! Thank you for your dedication and valuable contributions. 🎊`,
          date: new Date(),
          time: "10:00", // 24-hour format for proper sorting
          category: "general",
          departmentId: null,
          createdBy: {
            firstName: "System",
            lastName: "Auto",
            employeeId: "AUTO-WORK-ANNIVERSARY",
            id: "system-work-anniversary"
          },
          expireInHours: 24,
          isActive: true,
          isDeleted: false,
          isAutoGenerated: true,
          announcementType: "work_anniversary",
          celebrantId: user._id,
          celebrantInfo: {
            name: `${user.firstName} ${user.lastName}`,
            employeeId: user.employeeId,
            department: user.department?.name,
            yearsOfService: yearsOfService
          }
        };
      });
    } catch (error) {
      console.error('Error fetching work anniversary announcements:', error);
      return [];
    }
  }

  /**
   * Get marriage anniversary announcements for today
   * @param {number} month - Month to check
   * @param {number} day - Day to check
   * @param {string} userTeam - Team filter (SD or KAP)
   */
  async getMarriageAnniversaryAnnouncements(month, day, userTeam = null) {
    try {
      // Find users with marriage anniversaries today
      const query = {
        isDeleted: false,
        userDetails: { $exists: true, $ne: null },
        status: { $in: ["probation", "onroll"] }
      };

      // Add team filter if specified
      if (userTeam) {
        query.team = userTeam;
      }

      const marriageAnniversaryUsers = await User.find(query)
        .populate({
          path: 'userDetails',
          select: 'personalInfo'
        })
        .select('firstName lastName employeeId department team');
      
      const todayMarriageAnniversaries = marriageAnniversaryUsers.filter(user => {
        const marriageDate = user.userDetails?.personalInfo?.marriageDate;
        if (!marriageDate) return false;
        
        const marriageDateObj = new Date(marriageDate);
        const marriageMonth = marriageDateObj.getMonth() + 1;
        const marriageDay = marriageDateObj.getDate();
        
        // Only show for marriages that happened in previous years
        const marriageYear = marriageDateObj.getFullYear();
        const currentYear = new Date().getFullYear();
        
        return marriageMonth === month && 
               marriageDay === day && 
               marriageYear < currentYear;
      });
      
      return todayMarriageAnniversaries.map(user => {
        const marriageDate = new Date(user.userDetails.personalInfo.marriageDate);
        const yearsMarried = new Date().getFullYear() - marriageDate.getFullYear();
        const yearText = yearsMarried === 1 ? 'year' : 'years';
        
        return {
          _id: `marriage-anniversary-${user._id}`,
          title: `🤍ྀི Marriage Anniversary - ${user.firstName} ${user.lastName}`,
          content: `Congratulations to ${user.firstName} ${user.lastName} on ${yearsMarried} ${yearText} of marriage! Wishing you continued happiness and love. 💕`,
          date: new Date(),
          time: "11:00", // 24-hour format for proper sorting
          category: "general",
          departmentId: null,
          createdBy: {
            firstName: "System",
            lastName: "Auto",
            employeeId: "AUTO-MARRIAGE-ANNIVERSARY",
            id: "system-marriage-anniversary"
          },
          expireInHours: 24,
          isActive: true,
          isDeleted: false,
          isAutoGenerated: true,
          announcementType: "marriage_anniversary",
          celebrantId: user._id,
          celebrantInfo: {
            name: `${user.firstName} ${user.lastName}`,
            employeeId: user.employeeId,
            yearsMarried: yearsMarried
          }
        };
      });
    } catch (error) {
      console.error('Error fetching marriage anniversary announcements:', error);
      return [];
    }
  }
}

module.exports = new AnniversaryAnnouncementService();